version: '3'

services:

  # generates keycloak
  key_cloak:
    image: key_cloak
    container_name: key_cloak
    build:
      context: ./keycloak
    ports:
      - 9996:9996
    restart: on-failure

  # generates ui server
  ui_server:
    image: ui_server
    container_name: ui_server
    build:    
      context: ./ui_server
    ports:
      - 9998:9998
    restart: on-failure

  # generates fastapi
  fast_api:
    image: fast_api
    container_name: fast_api
    build:
      context: ./APIs
    ports:
      - 8000:8000
    restart: on-failure
  
  # generates keycloak
  torn_router:
    image: torn_router
    container_name: torn_router
    build:
      context: ./tornRouter
    ports:
      - 9999:9999
    restart: on-failure
